import { Card, CardId } from "./type/card";
import { SeatId } from "./type/seat";

export const MOCK_SERVER_URL = "ws://mock.server.com";

export const seatIds: SeatId[] = [1, 2, 3, 4, 5, 6];

export const cards: Card[] = [
  // NumberCards Red
  { id: 1, kind: "NumberCard", color: "red", number: 0 },
  { id: 2, kind: "NumberCard", color: "red", number: 1 },
  { id: 3, kind: "NumberCard", color: "red", number: 1 },
  { id: 4, kind: "NumberCard", color: "red", number: 2 },
  { id: 5, kind: "NumberCard", color: "red", number: 2 },
  { id: 6, kind: "NumberCard", color: "red", number: 3 },
  { id: 7, kind: "NumberCard", color: "red", number: 3 },
  { id: 8, kind: "NumberCard", color: "red", number: 4 },
  { id: 9, kind: "NumberCard", color: "red", number: 4 },
  { id: 10, kind: "NumberCard", color: "red", number: 5 },
  { id: 11, kind: "NumberCard", color: "red", number: 5 },
  { id: 12, kind: "NumberCard", color: "red", number: 6 },
  { id: 13, kind: "NumberCard", color: "red", number: 6 },
  { id: 14, kind: "NumberCard", color: "red", number: 7 },
  { id: 15, kind: "NumberCard", color: "red", number: 7 },
  { id: 16, kind: "NumberCard", color: "red", number: 8 },
  { id: 17, kind: "NumberCard", color: "red", number: 8 },
  { id: 18, kind: "NumberCard", color: "red", number: 9 },
  { id: 19, kind: "NumberCard", color: "red", number: 9 },
  // NumberCards Blue
  { id: 20, kind: "NumberCard", color: "blue", number: 0 },
  { id: 21, kind: "NumberCard", color: "blue", number: 1 },
  { id: 22, kind: "NumberCard", color: "blue", number: 1 },
  { id: 23, kind: "NumberCard", color: "blue", number: 2 },
  { id: 24, kind: "NumberCard", color: "blue", number: 2 },
  { id: 25, kind: "NumberCard", color: "blue", number: 3 },
  { id: 26, kind: "NumberCard", color: "blue", number: 3 },
  { id: 27, kind: "NumberCard", color: "blue", number: 4 },
  { id: 28, kind: "NumberCard", color: "blue", number: 4 },
  { id: 29, kind: "NumberCard", color: "blue", number: 5 },
  { id: 30, kind: "NumberCard", color: "blue", number: 5 },
  { id: 31, kind: "NumberCard", color: "blue", number: 6 },
  { id: 32, kind: "NumberCard", color: "blue", number: 6 },
  { id: 33, kind: "NumberCard", color: "blue", number: 7 },
  { id: 34, kind: "NumberCard", color: "blue", number: 7 },
  { id: 35, kind: "NumberCard", color: "blue", number: 8 },
  { id: 36, kind: "NumberCard", color: "blue", number: 8 },
  { id: 37, kind: "NumberCard", color: "blue", number: 9 },
  { id: 38, kind: "NumberCard", color: "blue", number: 9 },
  // NumberCards Green
  { id: 39, kind: "NumberCard", color: "green", number: 0 },
  { id: 40, kind: "NumberCard", color: "green", number: 1 },
  { id: 41, kind: "NumberCard", color: "green", number: 1 },
  { id: 42, kind: "NumberCard", color: "green", number: 2 },
  { id: 43, kind: "NumberCard", color: "green", number: 2 },
  { id: 44, kind: "NumberCard", color: "green", number: 3 },
  { id: 45, kind: "NumberCard", color: "green", number: 3 },
  { id: 46, kind: "NumberCard", color: "green", number: 4 },
  { id: 47, kind: "NumberCard", color: "green", number: 4 },
  { id: 48, kind: "NumberCard", color: "green", number: 5 },
  { id: 49, kind: "NumberCard", color: "green", number: 5 },
  { id: 50, kind: "NumberCard", color: "green", number: 6 },
  { id: 51, kind: "NumberCard", color: "green", number: 6 },
  { id: 52, kind: "NumberCard", color: "green", number: 7 },
  { id: 53, kind: "NumberCard", color: "green", number: 7 },
  { id: 54, kind: "NumberCard", color: "green", number: 8 },
  { id: 55, kind: "NumberCard", color: "green", number: 8 },
  { id: 56, kind: "NumberCard", color: "green", number: 9 },
  { id: 57, kind: "NumberCard", color: "green", number: 9 },
  // NumberCards Yellow
  { id: 58, kind: "NumberCard", color: "yellow", number: 0 },
  { id: 59, kind: "NumberCard", color: "yellow", number: 1 },
  { id: 60, kind: "NumberCard", color: "yellow", number: 1 },
  { id: 61, kind: "NumberCard", color: "yellow", number: 2 },
  { id: 62, kind: "NumberCard", color: "yellow", number: 2 },
  { id: 63, kind: "NumberCard", color: "yellow", number: 3 },
  { id: 64, kind: "NumberCard", color: "yellow", number: 3 },
  { id: 65, kind: "NumberCard", color: "yellow", number: 4 },
  { id: 66, kind: "NumberCard", color: "yellow", number: 4 },
  { id: 67, kind: "NumberCard", color: "yellow", number: 5 },
  { id: 68, kind: "NumberCard", color: "yellow", number: 5 },
  { id: 69, kind: "NumberCard", color: "yellow", number: 6 },
  { id: 70, kind: "NumberCard", color: "yellow", number: 6 },
  { id: 71, kind: "NumberCard", color: "yellow", number: 7 },
  { id: 72, kind: "NumberCard", color: "yellow", number: 7 },
  { id: 73, kind: "NumberCard", color: "yellow", number: 8 },
  { id: 74, kind: "NumberCard", color: "yellow", number: 8 },
  { id: 75, kind: "NumberCard", color: "yellow", number: 9 },
  { id: 76, kind: "NumberCard", color: "yellow", number: 9 },
  // ForceWildCards
  { id: 77, kind: "ForceWildCard", selectColor: "red" },
  { id: 78, kind: "ForceWildCard", selectColor: "blue" },
  { id: 79, kind: "ForceWildCard", selectColor: "green" },
  { id: 80, kind: "ForceWildCard", selectColor: "yellow" },
  // Action Cards Red
  { id: 81, kind: "ReverseCard", color: "red" },
  { id: 82, kind: "ReverseCard", color: "red" },
  { id: 83, kind: "DrawTwoCard", color: "red" },
  { id: 84, kind: "DrawTwoCard", color: "red" },
  { id: 85, kind: "SkipCard", color: "red" },
  { id: 86, kind: "SkipCard", color: "red" },
  // Action Cards Blue
  { id: 87, kind: "ReverseCard", color: "blue" },
  { id: 88, kind: "ReverseCard", color: "blue" },
  { id: 89, kind: "DrawTwoCard", color: "blue" },
  { id: 90, kind: "DrawTwoCard", color: "blue" },
  { id: 91, kind: "SkipCard", color: "blue" },
  { id: 92, kind: "SkipCard", color: "blue" },
  // Action Cards Green
  { id: 93, kind: "ReverseCard", color: "green" },
  { id: 94, kind: "ReverseCard", color: "green" },
  { id: 95, kind: "DrawTwoCard", color: "green" },
  { id: 96, kind: "DrawTwoCard", color: "green" },
  { id: 97, kind: "SkipCard", color: "green" },
  { id: 98, kind: "SkipCard", color: "green" },
  // Action Cards Yellow
  { id: 99, kind: "ReverseCard", color: "yellow" },
  { id: 100, kind: "ReverseCard", color: "yellow" },
  { id: 101, kind: "DrawTwoCard", color: "yellow" },
  { id: 102, kind: "DrawTwoCard", color: "yellow" },
  { id: 103, kind: "SkipCard", color: "yellow" },
  { id: 104, kind: "SkipCard", color: "yellow" },
  // Wild Cards
  { id: 105, kind: "WildCard" },
  { id: 106, kind: "WildCard" },
  { id: 107, kind: "WildCard" },
  { id: 108, kind: "WildCard" },
  // Wild Draw Four Cards
  { id: 109, kind: "WildDrawFourCard" },
  { id: 110, kind: "WildDrawFourCard" },
  { id: 111, kind: "WildDrawFourCard" },
  { id: 112, kind: "WildDrawFourCard" },
];

export const cardRelation: Record<CardId, Card> = cards.reduce(
  (acc, card) => {
    acc[card.id] = card;
    return acc;
  },
  {} as Record<CardId, Card>,
);
